name: 'Sanity checks'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_test:
    name: 'Build crate'
    runs-on:
      - 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          set -euxo pipefail
          cargo build --release --all-features